# Makefile - בונה את קובץ ההרצה 'assembler' מכל קבצי המקור ב-src/sources,
# עם קבצי הכותרת ב-src/Headers.
#
# הדגלים -Wall -ansi -pedantic נדרשים במפורש בהגדרת הפרויקט: הקוד חייב
# להתקמפל תחת תקן ANSI C (C89) בלי אף אזהרה או הערה מהמהדר.

CC = gcc
CFLAGS = -Wall -ansi -pedantic -g


clean:
	rm -f tests/*.am tests/*.ob tests/*.ent tests/*.ext